=== noear/waad/waad-plus/src/main/resources/org/noear/waad/xml/waad-mapper.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!--

               Copyright 2009-2018 the original author or authors.

               Licensed under the Apache License, Version 2.0 (the "License");
               you may not use this file except in compliance with the License.
               You may obtain a copy of the License at

                  http://www.apache.org/licenses/LICENSE-2.0

               Unless required by applicable law or agreed to in writing, software
               distributed under the License is distributed on an "AS IS" BASIS,
               WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
               See the License for the specific language governing permissions and
               limitations under the License.

        -->
        <!ELEMENT mapper (sql*)+>
        <!ATTLIST mapper
                namespace CDATA #REQUIRED
                proxy CDATA #IMPLIED
                import CDATA #IMPLIED
                baseMapper CDATA #IMPLIED
                db CDATA #IMPLIED
                >



        <!ELEMENT sql (#PCDATA | if | for | trim | ref)*>
        <!ATTLIST sql
                id ID #REQUIRED
                param CDATA #IMPLIED
                declare CDATA #IMPLIED
                return CDATA #IMPLIED

                remarks CDATA #IMPLIED

                caching CDATA #IMPLIED
                cacheClear CDATA #IMPLIED
                cacheTag CDATA #IMPLIED
                usingCache CDATA #IMPLIED
                >

        <!ELEMENT if (#PCDATA | if | for | trim | ref)*>
        <!ATTLIST if
                test CDATA #REQUIRED
                >

        <!ELEMENT for (#PCDATA | if | for | trim | ref)*>
        <!ATTLIST for
                var CDATA #REQUIRED
                items CDATA #REQUIRED
                sep CDATA #IMPLIED
                >

        <!ELEMENT trim (#PCDATA | if | for | trim | ref)*>
        <!ATTLIST trim
                trimStart CDATA #IMPLIED
                trimEnd CDATA #IMPLIED
                prefix CDATA #IMPLIED
                suffix CDATA #IMPLIED
                >

        <!ELEMENT ref (#PCDATA)*>
        <!ATTLIST ref
                sql IDREF #REQUIRED
                >

=== noear/waad/_test/src/main/resources/bak/UserMapper.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE mapper PUBLIC "-//noear.org//DTD Mapper 3.0//EN" "http://noear.org/dtd/waad-mapper.dtd">

<mapper namespace="waaddemo2.xmlsql2" db="db_sword">

    <!-- user_whitelist -->
    <sql id="user_whitelist_update" return="int"  note="更新白名单信息">
        UPDATE `user_blacklist`
        SET `update_fulltime` = @{update_fulltime:Date},
        <if test="user_id > 0">
            `user_id` = @{user_id:long},
        </if>
        <if test="name?!">
            `name` = @{name:String},
        </if>
        <if test="is_reg > 0">
            `is_reg` = @{is_reg:int},
        </if>

        <if test="auth_status >= 0">
            `auth_status` = @{auth_status:int},
        </if>
        <if test="order_status >= 0">
            `order_status` = @{order_status:int},
        </if>
        <if test="ava_amt gt 0">
            `ava_amt` = @{ava_amt:double},
        </if>
        <if test="finish_times gt 0">
            `finish_times` = `finish_times` + 1,
        </if>
        `update_date` = @{update_date:int}
        WHERE `mobile` = @{mobile:String};
    </sql>
</mapper>

=== noear/waad/_test/src/main/resources/bak/test.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE mapper PUBLIC "-//noear.org//DTD Mapper 3.0//EN" "http://noear.org/dtd/waad-mapper.dtd">
<mapper namespace="waaddemo2.xmlsql2"
        import="waad_demo.mapper.*">
    <sql id="user_add" return="List[Long]"
         param="m:UserModel,sex:int"
         remarks="添加用户"
         cacheClear="user_${m.user_id}"><![CDATA[
        INSERT user(user_id,mobile,sex) VALUES(@{m.user_id},@{m.mobile},@{sex})
    ]]></sql>

    <sql id="user_add3" return="long"
         param="m:UserModel,sex:int"
         remarks="添加用户"
         cacheClear="user_${m.user_id}">
        INSERT user
        <trim prefix="(" suffix=")" trimEnd=",">
            user_id,sex,
            <if test="m.mobile??">
                mobile,
            </if>
        </trim>
        VALUES
        <trim prefix="(" suffix=")" trimEnd=",">
            @{m.user_id},${sex},
            <if test="m.mobile != null">
                @{m.mobile},
            </if>
        </trim>
    </sql>

    <sql id="user_add_for" return="long" remarks="批量添加用户3">
        INSERT user(id,mobile,sex) VALUES
        <for var="m:UserModel" sep="#" items="list">
            (@{m.user_id},@{m.mobile},@{m.sex})
        </for>
    </sql>


    <sql id="user_set" return="long" remarks="更新用户"><![CDATA[
        UPDATE user SET sex=1 WHERE id IN(@{user_list:List[Integer]})
    ]]></sql>

    <sql id="user_add_for2" return="long" remarks="批量添加用户3">
        INSERT user(id,mobile,sex) VALUES
        <for var="m:UserModel" items="list">
            <if test="m.users != null">
                <for var="m2:UserModel" items="m.users">
                    (@{m2.user_id},@{m2.mobile},@{m2.sex})
                </for>
            </if>
        </for>
    </sql>
</mapper>

=== noear/waad/_test/src/main/resources/bak/UserAccountMapper.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE mapper PUBLIC "-//noear.org//DTD Mapper 3.0//EN" "http://noear.org/dtd/waad-mapper.dtd">

<mapper namespace="zm.data.code.pepper.api.dso.db.mapper"
        import="zm.data.code.pepper.api.models.db.*"
        db="db_pepper">

    <!-- user_account -->

    <sql id="add_user_account"
         return="long"
         caching="cache_pepper"
         cacheClear="user_account_user_id_${user_id}"
         remarks="新增用户账户">
        INSERT INTO `user_account` (`account_id`, `user_id`, `mobile`, `agroup_id`, `ugroup_id`, `app_id`, `type`,
        `balance`, `accumulation`, `create_date`, `create_fulltime`, `update_date`, `update_fulltime`)
        VALUES (@{account_id:long}, @{user_id:long}, @{mobile:String}, @{agroup_id:int}, @{ugroup_id:int},
        @{app_id:int}, @{type:int}, @{balance:String}, @{accumulation:String}, @{create_date:int},
        @{create_fulltime:Date}, @{update_date:int}, @{update_fulltime:Date})
    </sql>

    <sql id="user_account_plus_balance"
         caching="cache_pepper"
         cacheClear="user_account_user_id_${user_id}"
         remarks="账户余额修改"
         declare="trans_type:int">
        UPDATE `user_account` SET `balance` = `balance` + @{transaction:String},
        <if test="transaction?!">
            <if test="trans_type != 5">
                `accumulation` = `accumulation` + @{transaction:String},
            </if>
        </if>
        `update_date` = @{update_date:int}, `update_fulltime` = @{update_fulltime:Date} WHERE `user_id` =
        @{user_id:long} AND `type` = @{type:int}
    </sql>

    <sql id="get_user_account_by_user_id_and_type"
         return="UserAccountModel"
         caching="cache_pepper"
         cacheTag="user_account_user_id_${user_id}"
         remarks="获取账户">
        SELECT * FROM `user_account` WHERE `user_id` = @{user_id:long} AND `type` = @{type:int} LIMIT 1;
    </sql>

    <!-- user_account_journal -->

    <sql id="add_user_account_journal"
         return="long"
         caching="cache_pepper"
         cacheClear="user_account_user_id_${user_id}"
         remarks="新增用户账户流水">
        INSERT INTO `user_account_journal` (`journal_id`, `user_id`, `agroup_id`, `ugroup_id`, `app_id`, `mobile`,
        `type`, `status`, `trans_type`, `trans_id`, `extra`, `transaction`, `balance`, `create_date`, `create_fulltime`,
        `update_date`, `update_fulltime`)
        VALUES (@{journal_id:long}, @{user_id:long}, @{agroup_id:int}, @{ugroup_id:int}, @{app_id:int},
        @{mobile:String}, @{type:int}, @{status:int}, @{trans_type:int}, @{trans_id:long}, @{extra:String},
        @{transaction:String}, @{balance:String}, @{create_date:int}, @{create_fulltime:Date}, @{update_date:int},
        @{update_fulltime:Date})
    </sql>

    <sql id="get_user_account_journal_by_trans_type_paginated"
         return="List[UserAccountJournalModel]"
         caching="cache_pepper"
         cacheTag="user_account_user_id_${user_id}"
         remarks="分页获取账户流水">
        SELECT * FROM `user_account_journal` WHERE `user_id` = @{user_id:long} AND `type` = @{type:int}
        <if test="journal_id > 0">
            <![CDATA[
                AND `journal_id` < @{journal_id:long}
            ]]>
        </if>
        AND `trans_type` = @{trans_type:int} ORDER BY `journal_id` DESC LIMIT @{limit:int}
    </sql>


    <sql id="get_user_account_journal_by_trans_type_paginated2"
         return="List[UserAccountJournalModel]"
         caching="cache_pepper"
         cacheTag="user_account_user_id_${user_id}"
         remarks="分页获取账户流水">
        SELECT * FROM `user_account_journal` WHERE `user_id` = @{user_id:long} AND `type` = @{type:int}
        <if test="journal_id > 0">
            <![CDATA[
                AND `journal_id` < @{journal_id:long}
            ]]>
        </if>
        AND `trans_type` IN (@{trans_types:Iterable[Integer]}) ORDER BY `journal_id` DESC LIMIT @{limit:int}
    </sql>

    <sql id="update_user_account_journal"
         declare="user_id:long"
         caching="cache_pepper"
         cacheClear="user_account_journal_${journal_id}"
         remarks="更新用户账户流水状态">
        UPDATE `user_account_journal` SET `status` = @{status:int},`extra` = @{extra:String}, `update_date` =
        @{update_date:int},
        `update_fulltime` = @{update_fulltime:Date} WHERE journal_id = @{journal_id:long};
    </sql>

    <sql id="get_user_account_journal_by_id"
         return = "UserAccountJournalModel"
         caching="cache_pepper"
         cacheTag="user_account_journal_${journal_id}"
         remarks="分页获取账户流水">
        SELECT * FROM `user_account_journal` WHERE journal_id =  @{journal_id:long} limit 1;
    </sql>



    <sql id="get_account_journal_by_time"
         return="List[UserAccountJournalModel]">
        select * from user_account_journal where create_date = @{create_date:Integer}
        <![CDATA[
         and create_fulltime < @{create_fullTime:Date}
         ]]>
        and status = 1
        and trans_type in (3,6,7,8,9,10,13)
        order by journal_id asc
    </sql>


    <sql id="freeze_user_account"
         caching="cache_pepper"
         cacheClear="user_account_user_id_${user_id}"
         remarks="账户余额冻结">
        update user_account set balance = balance - @{transaction:String},freeze_balance = freeze_balance +
        @{transaction:String} where `user_id` =
        @{user_id:long} AND `type` = @{type:int} and balance >= @{transaction:String};
    </sql>

    <sql id="un_freeze_user_account"
         caching="cache_pepper"
         cacheClear="user_account_user_id_${user_id}"
         remarks="账户余额解冻">
        update user_account set balance = balance + @{transaction:String} ,freeze_balance - @{transaction:String}  where `user_id` =
        @{user_id:long} AND `type` = @{type:int} and freeze_balance >= @{transaction:String};
    </sql>
</mapper>

=== noear/waad/_test/src/main/resources/waad/test.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE mapper PUBLIC "-//noear.org//DTD Mapper 3.0//EN" "http://noear.org/dtd/waad-mapper.dtd">
<mapper db="db" namespace="waaddemo2.xmlsql2.test">
    <sql id="appx_get" remarks="随便取条数据的ID" return="int">select app_id from appx limit 1</sql>

    <sql cacheTag="app_${app_id}" caching="test" id="appx_get2" remarks="根据id取条数据" return="webapp.model.AppxModel"
         usingCache="300">select * from appx where app_id = @{app_id:int} limit 1
    </sql>

    <sql cacheClear="test" id="appx_get3" remarks="取一批ID" return="Map">select * from ${tb:String} where app_id =
        @{app_id:int} limit 1
    </sql>

    <sql id="appx_getlist" return="List[webapp.model.AppxModel]">select * from appx where app_id>@{app_id:int} order by
        app_id asc limit 4
    </sql>

    <sql id="appx_getids" return="List[Integer]">select app_id from appx limit 4</sql>

    <sql id="appx_udp" return="int" declare="tag:String,tag1:String">
        select app_id from appx
        <if test="tag?! and tag1??">
            where app_id > 10
        </if>
        limit 4
    </sql>

    <sql id="appx_udp2" return="int" declare="tag:String,tag1:String">
        select app_id from appx
        <if test="tag ?! and tag1 ??">
            where app_id > 10
        </if>
        limit 4
    </sql>
</mapper>
